#!/bin/sh

NPROC=`nproc`
THREADS=${THREADS:-$NPROC}

echo "Building using $THREADS threads"

MAKE=${MAKE:-make}

WOOT_TOP_DIR=`pwd`
BINUTILS_DIR=$WOOT_TOP_DIR/user/binutils
GCC_DIR=$WOOT_TOP_DIR/user/gcc

echo "Building libc"
$MAKE -j$THREADS -C user/libc

echo "Building binutils for cross compilation"
rm -rf $BINUTILS_DIR/build-cross
cd $BINUTILS_DIR && \
./configure-cross && \
make -j$THREADS -C build-cross && \
make -C build-cross install

echo "Building GCC cross compiler"
rm -rf $GCC_DIR/build-cross
cd $GCC_DIR && \
./configure-cross && \
make -j$THREADS -C build-cross all-gcc all-target-libgcc all-target-libstdc++-v3 && \
make -C build-cross install-gcc install-target-libgcc install-target-libstdc++-v3

