#!/bin/sh

THIS_DIR=`pwd`
WOOT_TOP_DIR=`realpath $THIS_DIR/../..`
BUILD_DIR="$WOOT_TOP_DIR/user/gcc/build-cross"
INSTALL_DIR="$WOOT_TOP_DIR/cross-root"
#CONFIG_SCRIPT="../gcc-7.1.0/configure"
CONFIG_SCRIPT="../gcc-9.1.0/configure"
TARGET_ARCH="x86_64-woot"
CONFIG_ARGS="\
--prefix=$INSTALL_DIR \
--target=$TARGET_ARCH \
--with-sysroot=$INSTALL_DIR \
--disable-nls \
--enable-languages=c,c++ \
--disable-multilib \
--disable-werror \
--enable-threads \
--enable-shared \
--enable-host-shared \
--disable-tm-clone-registry"

echo "Using WOOT root directory $WOOT_TOP_DIR"
echo "Build directory $BUILD_DIR"
echo "Install directory $INSTALL_DIR"

echo "Creating directory structure"
mkdir -p $BUILD_DIR

echo "Running configuration script"
cd $BUILD_DIR && $CONFIG_SCRIPT $CONFIG_ARGS

