#!/bin/sh

THIS_DIR=`pwd`
WOOT_TOP_DIR=`realpath $THIS_DIR/../..`
BUILD_DIR="$WOOT_TOP_DIR/user/gcc/build-cross"
INSTALL_DIR="$WOOT_TOP_DIR/cross-root"
CONFIG_SCRIPT="../gcc-7.1.0/configure"
TARGET_ARCH="x86_64-elf"
CONFIG_ARGS="\
--prefix=$INSTALL_DIR \
--target=$TARGET_ARCH \
--disable-nls \
--enable-languages=c,c++ \
--without-headers \
--disable-multilib \
--enable-threads"

echo "Using WOOT root directory $WOOT_TOP_DIR"
echo "Build directory $BUILD_DIR"
echo "Install directory $INSTALL_DIR"

echo "Creating directory structure"
mkdir -p $BUILD_DIR

echo "Running configuration script"
cd $BUILD_DIR && $CONFIG_SCRIPT $CONFIG_ARGS

