#!/bin/sh

THIS_DIR=`pwd`
WOOT_TOP_DIR=`realpath $THIS_DIR/../..`
BUILD_DIR="$WOOT_TOP_DIR/user/binutils/build-cross"
INSTALL_DIR="$WOOT_TOP_DIR/cross-root"
CONFIG_SCRIPT="../binutils-2.32/configure"
TARGET_ARCH="x86_64-woot"
CONFIG_ARGS="\
--prefix=$INSTALL_DIR \
--with-sysroot=$INSTALL_DIR \
--target=$TARGET_ARCH \
--disable-nls \
--enable-shared \
--disable-multilib \
--disable-werror"

echo Using WOOT root directory $WOOT_TOP_DIR
echo Build directory $BUILD_DIR
echo Install directory $INSTALL_DIR

echo Creating directory structure
mkdir -p $BUILD_DIR
mkdir -p $INSTALL_DIR/$INCLUDE_DIR

echo Running configuration script
cd $BUILD_DIR && $CONFIG_SCRIPT $CONFIG_ARGS

