#include "SDL_video.h"
#include "../SDL_sysvideo.h"
#include "SDL_events.h"
#include "../../events/SDL_events_c.h"

#include "SDL_wootEvents.h"

#include <woot/ipc.h>
#include <woot/vkeys.h>
#include <woot/wm.h>

SDLKey vkToKeySym[256] =
{
    SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_BACKSPACE, SDLK_TAB, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_CLEAR, SDLK_RETURN, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0x00 - 0x0F; 0 - 15
    SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_PAUSE, SDLK_CAPSLOCK, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_ESCAPE, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0x10 - 0x1F; 16 - 31
    SDLK_SPACE, SDLK_PAGEUP, SDLK_PAGEDOWN, SDLK_END, SDLK_HOME, SDLK_LEFT, SDLK_UP, SDLK_RIGHT, SDLK_DOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_INSERT, SDLK_DELETE, SDLK_UNKNOWN, // 0x20 - 0x2F; 32 - 47
    SDLK_0, SDLK_1, SDLK_2, SDLK_3, SDLK_4, SDLK_5, SDLK_6, SDLK_7, SDLK_8, SDLK_9, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0x30 - 0x3F; 48 - 63
    SDLK_UNKNOWN, SDLK_a, SDLK_b, SDLK_c, SDLK_d, SDLK_e, SDLK_f, SDLK_g, SDLK_h, SDLK_i, SDLK_j, SDLK_k, SDLK_l, SDLK_m, SDLK_n, SDLK_o, // 0x40 - 0x4F; 64 - 79
    SDLK_p, SDLK_q, SDLK_r, SDLK_s, SDLK_t, SDLK_u, SDLK_v, SDLK_w, SDLK_x, SDLK_y, SDLK_z, SDLK_LSUPER, SDLK_RSUPER, SDLK_MENU, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0x50 - 0x5F; 80 - 95
    SDLK_KP0, SDLK_KP1, SDLK_KP2, SDLK_KP3, SDLK_KP4, SDLK_KP5, SDLK_KP6, SDLK_KP7, SDLK_KP8, SDLK_KP9, SDLK_KP_MULTIPLY, SDLK_KP_PLUS, SDLK_UNKNOWN, SDLK_KP_MINUS, SDLK_KP_PERIOD, SDLK_KP_DIVIDE, // 0x60 - 0x6F; 96 - 111
    SDLK_F1, SDLK_F2, SDLK_F3, SDLK_F4, SDLK_F5, SDLK_F6, SDLK_F7, SDLK_F8, SDLK_F9, SDLK_F10, SDLK_F11, SDLK_F12, SDLK_F13, SDLK_F14, SDLK_F15, SDLK_UNKNOWN, // 0x70 - 0x7F; 112 - 127
    SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0x80 - 0x8F; 128 - 143
    SDLK_NUMLOCK, SDLK_SCROLLOCK, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0x90 - 0x9F; 144 - 159
    SDLK_LSHIFT, SDLK_RSHIFT, SDLK_LCTRL, SDLK_RCTRL, SDLK_LALT, SDLK_RALT, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0xA0 - 0xAF; 160 - 175
    SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_SEMICOLON, SDLK_EQUALS, SDLK_COMMA, SDLK_MINUS, SDLK_PERIOD, SDLK_SLASH, // 0xB0 - 0xBF; 176 - 191
    SDLK_BACKQUOTE, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0xC0 - 0xCF; 192 - 207
    SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_LEFTBRACKET, SDLK_BACKSLASH, SDLK_RIGHTBRACKET, SDLK_QUOTE, SDLK_UNKNOWN, // 0xD0 - 0xDF; 208 - 223
    SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, // 0xE0 - 0xEF; 224 - 239
    SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN, SDLK_UNKNOWN  // 0xF0 - 0xFF; 240 - 255
};

void WOOT_InitOSKeymap(_THIS)
{
    // nothing to be done here
}

void WOOT_PumpEvents(_THIS)
{
    ipcMessage_t msg;

    if(!this || !this->hidden || !this->hidden->window)
        return;

    wmWindow_t *wnd = this->hidden->window;
    int wndId = wmGetWindowId(wnd);
    SDL_Event sdlEvent;

    while(ipcGetMessage(&msg, 0) >= 0)
    {
        ipcProcessMessage(&msg);
        if(msg.Number == MSG_WM_EVENT)
        {
            wmEvent_t *event = (wmEvent_t *)msg.Data;
            if(event->WindowId == wndId)
            {
                wmProcessEvent(wnd, event);
                if(event->Type == WM_EVT_KEYBOARD)
                {
                    Uint8 state = event->Keyboard.Flags & WM_EVT_KB_RELEASED ? SDL_RELEASED : SDL_PRESSED;
                    SDL_keysym key;
                    key.sym = vkToKeySym[event->Keyboard.Key];
                    SDL_PrivateKeyboard(state, &key);
                }
                else if(event->Type == WM_EVT_CLOSE)
                {
                    sdlEvent.type = SDL_QUIT;
                    SDL_PushEvent(&sdlEvent);
                }
            }
        }
    }
}
