#!/bin/sh

#!/bin/sh

COMMAND=clang++

ARGS="-Wno-unused-command-line-argument \
-Wno-bitwise-op-parentheses \
-Wno-shift-op-parentheses \
-fno-stack-protector \
-ffreestanding -nostdinc -nostdinc++ -nostdlib -fno-exceptions -fno-rtti \
-Wl,-z,max-page-size=4096 \
-I$WOOT_TOP_DIR/user/libsyscalls \
-I$WOOT_TOP_DIR/user/libc/include \
-I$WOOT_TOP_DIR/user/libz/include \
-I$WOOT_TOP_DIR/user/libpng/include \
-I$WOOT_TOP_DIR/user/libfreetype/include/freetype2 \
-I$WOOT_TOP_DIR/user/libwoot \
-L$WOOT_TOP_DIR/user/libsyscalls \
-L$WOOT_TOP_DIR/user/libc/lib \
-L$WOOT_TOP_DIR/user/libz/lib \
-L$WOOT_TOP_DIR/user/libpng/lib \
-L$WOOT_TOP_DIR/user/libfreetype/lib \
-L$WOOT_TOP_DIR/user/libwoot"

$COMMAND $ARGS "$@"
